<?php $this->layout('layout::default', ['title' => 'Home']) ?>

<h1>Localizador de pessoas</h1>

<div class="input-group mb-3">
    <input 
        type="text" 
        id="txt-localizar"
        class="form-control"
        placeholder="Digite a conta do twitter que esta procurando. Ex: @celebryts">
  <div class="input-group-append">
    <button class="btn btn-primary input-group" id="btn-localizar">Localizar</button>
  </div>
</div>

<div class="row">
    <div class="info">
    </div>
</div>

